export const AUTH_AUTHENTICATED = 'AUTH_AUTHENTICATED';
export const AUTH_AUTHENTICATING = 'AUTH_AUTHENTICATING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ALIASES_DATA_FETCH = 'ALIASES_DATA_FETCH';
export const ALIASES_DATA_RECEIVED = 'ALIASES_DATA_RECEIVED';
export const ALIASES_DATA_ERROR = 'ALIASIS_DATA_ERROR';
export const ALIAS_DATA_ADD = 'ALIAS_DATA_ADD';

export const AREAS_DATA_FETCH = 'AREAS_DATA_FETCH';
export const AREAS_DATA_RECEIVED = 'AREAS_DATA_RECEIVED';
export const AREAS_DATA_ERROR = 'AREAS_DATA_ERROR';
export const AREA_DATA_ADD = 'AREAS_DATA_ADD';
export const AREA_DATA_EDIT = 'AREA_DATA_EDIT';
export const AREA_DATA_DELETE = 'AREA_DATA_DELETE';

export const CLASSES_DATA_FETCH = 'CLASSES_DATA_FETCH';
export const CLASSES_DATA_RECEIVED = 'CLASSES_DATA_RECEIVED';
export const CLASSES_DATA_ERROR = 'CLASSES_DATA_ERROR';

export const DASHBOARD_DATA_FETCH = 'DASHBOARD_DATA_FETCH';
export const DASHBOARD_DATA_RECEIVED = 'DASHBOARD_DATA_RECEIVED';
export const DASHBOARD_DATA_ERROR = 'DASHBOARD_DATA_ERROR';

export const DRAWER_OPEN = 'DRAWER_OPEN';
export const DRAWER_CLOSE = 'DRAWER_CLOSE';
export const DRAWER_CLOSE_DEFAULT = 'DRAWER_CLOSE_DEFAULT';
export const DRAWER_OPEN_DEFAULT = 'DRAWER_OPEN_DEFAULT';
export const DRAWER_EXPAND = 'DRAWER_EXPAND';
export const DRAWER_SELECTION = 'DRAWER_SELECTION';
export const DRAWER_VIEW = 'DRAWER_VIEW';

export const DOMAIN_DATA_ADD = 'DOMAIN_DATA_ADD';
export const DOMAIN_DATA_EDIT = 'DOMAIN_DATA_EDIT';
export const DOMAIN_DATA_FETCH = 'DOMAIN_DATA_FETCH';
export const DOMAIN_DATA_RECEIVED = 'DOMAIN_DATA_RECEIVED';
export const DOMAIN_DATA_ERROR = 'DOMAIN_DATA_ERROR';

export const FOLDERS_DATA_FETCH = 'FOLDERS_DATA_FETCH';
export const FOLDERS_DATA_RECEIVED = 'FOLDERS_DATA_RECEIVED';
export const FOLDERS_DATA_ERROR = 'FOLDERS_DATA_ERROR';
export const FOLDER_DATA_ADD = 'FOLDER_DATA_ADD';

export const FORWARDS_DATA_FETCH = 'FORWARDS_DATA_FETCH';
export const FORWARDS_DATA_RECEIVED = 'FORWARDS_DATA_RECEIVED';
export const FORWARDS_DATA_ERROR = 'FORWARDS_DATA_ERROR';

export const GROUPS_DATA_FETCH = 'GROUPS_DATA_FETCH';
export const GROUPS_DATA_RECEIVED = 'GROUPS_DATA_RECEIVED';
export const GROUPS_DATA_ERROR = 'GROUPS_DATA_ERROR';
export const GROUP_DATA_DELETE = 'GROUP_DATA_DELETE';
export const GROUP_DATA_EDIT = 'GROUP_DATA_EDIT';

export const MEMBERS_DATA_FETCH = 'MEMBERS_DATA_FETCH';
export const MEMBERS_DATA_RECEIVED = 'MEMBERS_DATA_RECEIVED';
export const MEMBERS_DATA_ERROR = 'MEMBERS_DATA_ERROR';

export const ORGS_DATA_FETCH = 'ORGS_DATA_FETCH';
export const ORGS_DATA_RECEIVED = 'ORGS_DATA_RECEIVED';
export const ORGS_DATA_ERROR = 'ORGS_DATA_ERROR';

export const MLISTS_DATA_FETCH = 'MLISTS_DATA_FETCH';
export const MLISTS_DATA_RECEIVED = 'MLISTS_DATA_RECEIVED';
export const MLISTS_DATA_ERROR = 'MLISTS_DATA_ERROR';

export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';

export const SERVICES_DATA_FETCH = 'SERVICES_DATA_FETCH';
export const SERVICES_DATA_RECEIVED = 'SERVICES_DATA_RECEIVED';
export const SERVICES_DATA_ERROR = 'SERVICES_DATA_ERROR';

export const USER_DATA_ADD = 'USER_DATA_ADD';
export const USER_DATA_EDIT = 'USER_DATA_EDIT';
export const USER_DATA_DELETE = 'USER_DATA_DELETE';
export const USERS_DATA_FETCH = 'USERS_DATA_FETCH';
export const USERS_DATA_RECEIVED = 'USERS_DATA_RECEIVED';
export const USERS_DATA_ERROR = 'USERS_DATA_ERROR';
export const USER_ALIASES_DATA_FETCH = 'USER_ALIASES_DATA_FETCH';
export const USER_ALIASES_DATA_RECEIVED = 'USER_ALIASES_DATA_RECEIVED';
export const USER_ALIASES_DATA_ERROR = 'USER_ALIASES_DATA_ERROR';
export const USER_ALIAS_DATA_ADD = 'USER_ALIAS_DATA_ADD';
