export const AUTH_AUTHENTICATED = 'AUTH_AUTHENTICATED';
export const AUTH_AUTHENTICATING = 'AUTH_AUTHENTICATING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const DRAWER_OPEN = 'DRAWER_OPEN';
export const DRAWER_CLOSE = 'DRAWER_CLOSE';
export const DRAWER_CLOSE_DEFAULT = 'DRAWER_CLOSE_DEFAULT';
export const DRAWER_OPEN_DEFAULT = 'DRAWER_OPEN_DEFAULT';
export const DRAWER_EXPAND = 'DRAWER_EXPAND';
export const DRAWER_SELECTION = 'DRAWER_SELECTION';

export const DOMAIN_DATA_ADD = 'DOMAIN_DATA_ADD';
export const DOMAIN_DATA_EDIT = 'DOMAIN_DATA_EDIT';
export const DOMAIN_DATA_FETCH = 'DOMAIN_DATA_FETCH';
export const DOMAIN_DATA_RECEIVED = 'DOMAIN_DATA_RECEIVED';
export const DOMAIN_DATA_ERROR = 'DOMAIN_DATA_ERROR';

export const USER_DATA_ADD = 'USER_DATA_ADD';
export const USER_DATA_EDIT = 'USER_DATA_EDIT';
export const USER_DATA_DELETE = 'USER_DELETE_USER';
export const USERS_DATA_FETCH = 'USERS_DATA_FETCH';
export const USERS_DATA_RECEIVED = 'USERS_DATA_RECEIVED';
export const USERS_DATA_ERROR = 'USERS_DATA_ERROR';
