export const AUTH_AUTHENTICATED = 'AUTH_AUTHENTICATED';
export const AUTH_AUTHENTICATING = 'AUTH_AUTHENTICATING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const DRAWER_OPEN = 'DRAWER_OPEN';
export const DRAWER_CLOSE = 'DRAWER_CLOSE';
export const DRAWER_CLOSE_DEFAULT = 'DRAWER_CLOSE_DEFAULT';
export const DRAWER_OPEN_DEFAULT = 'DRAWER_OPEN_DEFAULT';
export const DRAWER_EXPAND = 'DRAWER_EXPAND';
export const DRAWER_SELECTION = 'DRAWER_SELECTION';